# Generated by Django 2.2 on 2021-06-28 19:01

from django.db import models, migrations
from datetime import date


class Migration(migrations.Migration):
    def load_data(apps, schema_editor):
        PriceHistory = apps.get_model("historical_data", "PriceHistory")

        PriceHistory(date=date(2013, 11, 29),
                     price=1234.00,
                     volume=354.564,
                     #total_btc=12054375,
                     ).save()
        PriceHistory(date=date(2012, 11, 29),
                     price=12.15,
                     volume=187.947,
                     #total_btc=10504650,
                     ).save()

    dependencies = [
        ('historical_data', '0002_switch_to_decimals'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
